// flow-typed signature: a2c44770eb8fd8234f89c4454e1c57cc
// flow-typed version: <<STUB>>/jest-validate_v^20.0.3/flow_v0.53.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-validate'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-validate' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-validate/build-es5/condition' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/defaultConfig' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/deprecated' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/errors' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/exampleConfig' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/index' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/types' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/utils' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/validate' {
  declare module.exports: any;
}

declare module 'jest-validate/build-es5/warnings' {
  declare module.exports: any;
}

declare module 'jest-validate/build/condition' {
  declare module.exports: any;
}

declare module 'jest-validate/build/defaultConfig' {
  declare module.exports: any;
}

declare module 'jest-validate/build/deprecated' {
  declare module.exports: any;
}

declare module 'jest-validate/build/errors' {
  declare module.exports: any;
}

declare module 'jest-validate/build/exampleConfig' {
  declare module.exports: any;
}

declare module 'jest-validate/build/index' {
  declare module.exports: any;
}

declare module 'jest-validate/build/types' {
  declare module.exports: any;
}

declare module 'jest-validate/build/utils' {
  declare module.exports: any;
}

declare module 'jest-validate/build/validate' {
  declare module.exports: any;
}

declare module 'jest-validate/build/warnings' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-validate/build-es5/condition.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/condition'>;
}
declare module 'jest-validate/build-es5/defaultConfig.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/defaultConfig'>;
}
declare module 'jest-validate/build-es5/deprecated.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/deprecated'>;
}
declare module 'jest-validate/build-es5/errors.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/errors'>;
}
declare module 'jest-validate/build-es5/exampleConfig.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/exampleConfig'>;
}
declare module 'jest-validate/build-es5/index.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/index'>;
}
declare module 'jest-validate/build-es5/types.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/types'>;
}
declare module 'jest-validate/build-es5/utils.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/utils'>;
}
declare module 'jest-validate/build-es5/validate.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/validate'>;
}
declare module 'jest-validate/build-es5/warnings.js' {
  declare module.exports: $Exports<'jest-validate/build-es5/warnings'>;
}
declare module 'jest-validate/build/condition.js' {
  declare module.exports: $Exports<'jest-validate/build/condition'>;
}
declare module 'jest-validate/build/defaultConfig.js' {
  declare module.exports: $Exports<'jest-validate/build/defaultConfig'>;
}
declare module 'jest-validate/build/deprecated.js' {
  declare module.exports: $Exports<'jest-validate/build/deprecated'>;
}
declare module 'jest-validate/build/errors.js' {
  declare module.exports: $Exports<'jest-validate/build/errors'>;
}
declare module 'jest-validate/build/exampleConfig.js' {
  declare module.exports: $Exports<'jest-validate/build/exampleConfig'>;
}
declare module 'jest-validate/build/index.js' {
  declare module.exports: $Exports<'jest-validate/build/index'>;
}
declare module 'jest-validate/build/types.js' {
  declare module.exports: $Exports<'jest-validate/build/types'>;
}
declare module 'jest-validate/build/utils.js' {
  declare module.exports: $Exports<'jest-validate/build/utils'>;
}
declare module 'jest-validate/build/validate.js' {
  declare module.exports: $Exports<'jest-validate/build/validate'>;
}
declare module 'jest-validate/build/warnings.js' {
  declare module.exports: $Exports<'jest-validate/build/warnings'>;
}
